--- 
dist: bionic
matrix: 
  include: 
    - 
      before_install: 
        - "sudo apt install -y openjdk-11-jre"
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/bash"
      language: bash
      name: "Bash snippets using xenon-cli"
      script: 
        - "echo 'maybe later'"
    - 
      before_cache: 
        - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
        - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
      before_install: 
        - "sudo apt install -y openjdk-11-jre"
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/java"
      cache: 
        directories: 
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      jdk: openjdk11
      language: java
      name: "Java snippets that use xenon library directly"
      script: 
        - "./gradlew check"
    - 
      before_install: 
        - "sudo apt install -y openjdk-11-jre"
        - "docker pull nlesc/xenon-slurm:17"
        - "docker run --detach --publish 10022:22 --hostname slurm17 nlesc/xenon-slurm:17"
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/python"
        - "ls -l /home/travis/.ssh"
        - "chmod 644 /home/travis/.ssh/config"
        - "ls -l /home/travis/.ssh"
        - "ls -ld /home/travis/.ssh"
        - "chmod 700 /home/travis/.ssh"
        - "ls -ld /home/travis/.ssh"
        - java -jar /home/travis/virtualenv/python3.6.7/lib/xenon-grpc-3.0.0.jar -vvvvv
      install: 
        - "(git clone https://github.com/xenon-middleware/pyxenon.git && cd pyxenon && pip install .)"
        - "which xenon-grpc"
      language: python
      name: "Python snippets using pyxenon and xenon-grpc"
      script: 
        - "pytest tests/test_slurm_queues_getter.py"
      services: 
        - docker
notifications: 
  email: 
    on_failure: change
    on_succes: never
