--- 
before_cache: 
  - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
  - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
before_script:
  - "cd readthedocs/code-tabs/java"
cache: 
  directories: 
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
dist: bionic
jdk: 
  - openjdk11
language: java
notifications: 
  email: 
    on_failure: change
    on_succes: never
script: 
  - "./gradlew check"
sudo: false
