--- 
dist: bionic
matrix: 
  include: 
    - 
      before_install: 
        - "docker pull nlesc/xenon-slurm:17"
      before_script: 
        - "docker run --detach --publish 10022:22 --hostname slurm17 nlesc/xenon-slurm:17"
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/bash"
        - "docker images"
        - "docker ps -a"
      install: 
        - "sudo apt install -y openjdk-11-jre"
        - "wget https://github.com/xenon-middleware/xenon-cli/releases/download/v3.0.1/xenon-cli-shadow-3.0.1.tar"
        - "tar -xvf xenon-cli-shadow-3.0.1.tar"
        - "mkdir -p /home/travis/.local/bin/xenon"
        - "mv xenon-cli-shadow-3.0.1 /home/travis/.local/bin/xenon/"
        - "echo '' >> /home/travis/.bashrc"
        - "echo '# add xenon-cli directory to PATH' >> /home/travis/.bashrc"
        - "echo 'PATH=$PATH:/home/travis/.local/bin/xenon/xenon-cli-shadow-3.0.1/bin' >> /home/travis/.bashrc"
        - "source /home/travis/.bashrc"
        - "which xenon"
        - "ls -l /home/travis/.ssh"
        - "chmod 644 /home/travis/.ssh/config"
        - "rm /home/travis/.ssh/known_hosts"
        - "ls -l /home/travis/.ssh"
        - "ls -ld /home/travis/.ssh"
        - "chmod 700 /home/travis/.ssh"
        - "ls -ld /home/travis/.ssh"
      language: bash
      name: "Bash snippets using xenon-cli"
      script: 
        - # "xenon -vvvvvv scheduler slurm --location ssh://localhost:10022 --username xenon --password javagat --prop xenon.adaptors.schedulers.ssh.loadKnownHosts=false queues"
        - "bash travis.sh"
      services: 
        - docker
    - 
      before_cache: 
        - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
        - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
      before_install: 
        - "sudo apt install -y openjdk-11-jre"
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/java"
      cache: 
        directories: 
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      jdk: openjdk11
      language: java
      name: "Java snippets that use xenon library directly"
      script: 
        - "./gradlew check"
    - 
      before_install: 
        - "docker pull nlesc/xenon-slurm:17"
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/python"
        - "docker run --detach --publish 10022:22 --hostname slurm17 nlesc/xenon-slurm:17"
      install: 
        - "sudo apt install -y openjdk-11-jre"
        - "pip install -r readthedocs/code-tabs/python/requirements.txt"
        - "pip install -r readthedocs/code-tabs/python/requirements-dev.txt"
        - "ls -l /home/travis/.ssh"
        - "rm /home/travis/.ssh/known_hosts"
        - "chmod 644 /home/travis/.ssh/config"
        - "ls -l /home/travis/.ssh"
        - "ls -ld /home/travis/.ssh"
        - "chmod 700 /home/travis/.ssh"
        - "ls -ld /home/travis/.ssh"
        - "which xenon-grpc"
      language: python
      name: "Python snippets using pyxenon and xenon-grpc"
      script: 
        - "xenon-grpc -vvvvv & pytest tests/test_slurm_queues_getter.py"
      services: 
        - docker
notifications: 
  email: 
    on_failure: change
    on_succes: never
