--- 
dist: bionic
matrix: 
  include: 
    - 
      before_install:
        - sudo apt install -y openjdk-11-jre
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/bash"
      language: bash
      name: "Bash snippets using xenon-cli"
      script: 
        - "echo 'maybe later'"
    - 
      before_install:
        - sudo apt install -y openjdk-11-jre
      before_cache: 
        - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
        - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/java"
      cache: 
        directories: 
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      jdk: openjdk11
      language: java
      name: "Java snippets that use xenon library directly"
      script: 
        - "./gradlew check"
    - 
      before_install:
        - sudo apt install -y openjdk-11-jre
      before_script: 
        - "bash vm-prep/make-fixtures.sh"
        - "cd readthedocs/code-tabs/python"
      language: python
      name: "Python snippets using pyxenon and xenon-grpc"
      install:
        - (git clone https://github.com/xenon-middleware/pyxenon.git && cd pyxenon && pip install . )
      script: 
        - python setup.py test
notifications: 
  email: 
    on_failure: change
    on_succes: never

